
# see: https://hub.docker.com/_/jenkins/

# An error occurred during installation: No such plugin: cloudbees-folder
# see: http://stackoverflow.com/questions/37358775/jenkins-2-5-installation-error-an-error-occurred-during-installation-forbidden
# http://jenkins.local:18083/restart

# Find passowrd in console log after initial start.

version: '2.1'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
    image: home1oss/jenkins:2.60.1-alpine
    restart: always
    container_name: ${JENKINS_HOSTNAME:-jenkins.local}
    hostname: ${JENKINS_HOSTNAME:-jenkins.local}
    ports:
    - "${JENKINS_EXTERNAL_PORT:-18083}:${JENKINS_PORT:-8080}"
    - "50000:50000/tcp"
    volumes:
    - jenkins-master-volume:/var/jenkins_home
    environment:
    - JENKINS_SLAVE_AGENT_PORT=50000

volumes:
  jenkins-master-volume: {}

networks:
  default:
    external:
      name: oss-network
