
# see: https://wiki.jenkins-ci.org/display/JENKINS/Swarm+Plugin
# see: https://hub.docker.com/r/csanchez/jenkins-swarm-slave/
# see: https://github.com/carlossg/jenkins-swarm-slave-docker

# see: https://github.com/evarga/docker-images
# see: https://github.com/code-troopers/docker-jenkins-slaves

# see: https://github.com/yasn77/docker-jenkins-slave
# see: https://github.com/jenkinsci/docker-ssh-slave










version: '2.1'
services:
  jenkins-swarm-slave:
    build:
      context: .
      dockerfile: Dockerfile
    image: home1oss/jenkins-swarm-slave:2.2-xenial
    restart: always
    command: ["-username", "swarm", "-password", "swarm_pass", "-executors", "5"]
    container_name: ${JENKINS_SLAVE_HOSTNAME:-jenkins-swarm-slave.local}
    hostname: ${JENKINS_SLAVE_HOSTNAME:-jenkins-swarm-slave.local}
    external_links:
    - jenkins.local:jenkins.local
    - nexus.local:nexus.local
    - mvnsite.local:mvnsite.local
    volumes:
    - jenkins-swarm-slave-volume:/home/jenkins-slave
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - JENKINS_PORT_8080_TCP_ADDR=${JENKINS_PORT_8080_TCP_ADDR:-jenkins.local}
    - JENKINS_PORT_8080_TCP_PORT=${JENKINS_PORT_8080_TCP_PORT:-8080}
    - INFRASTRUCTURE_CONF_GIT_TOKEN=${INFRASTRUCTURE_CONF_GIT_TOKEN:-your_INFRASTRUCTURE_CONF_GIT_TOKEN}

volumes:
  jenkins-swarm-slave-volume: {}

networks:
  default:
    external:
      name: oss-network
